name: test

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ ubuntu-latest ]
        # Oldest one based on NEP-29 and latest one.
        # See https://numpy.org/neps/nep-0029-deprecation_policy.html
        numpy-version: [ "1.26", "2" ]
      fail-fast: false

    steps:
      - uses: "actions/checkout@v4"

      - name: Set up Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Cache pip dependencies
        uses: "actions/cache@v4"
        id: "cache"
        with:
          path: "${{ env.pythonLocation }}/.cache/pip"
          key: "test-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'requirements/*') }}"
          restore-keys: |
            test-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements/requirements-dev.txt
          pip install ./

      - name: Reinstall Utide
        run: |
          pip install --upgrade setuptools
          pip install --force-reinstall utide

      - name: Run tests
        run: pytest tests/notebooks_test.py -v --cov=analysea --color=yes --nb-exec-timeout 50
        env:
          PYTHONPATH: ${{ github.workspace }}/tests
